### ISSUE TITLE
Request: Add system and python requirements 

### ISSUE THREAD

**Issue by avinassh** [DarkNand/subliminal-minimal-gui#1]
Hi, can you please add what all system requirements are required and also required pypi packages? Thank you!

**Comment by Netanel-M** [comment]
Rewrote the readme and also enhanced the code to support newer providers.
just pip install subliminal and you should get everything you need (on linux)
If you're on windows, or you don't have pygobject you're going to have to install that too.

**Comment by avinassh** [comment]
Thank you very much :D

**Comment by Netanel-M** [comment]
I've also recently started working on the GUI again. It now supports a config file so you can set your own languages/providers and the defaults for them.
You're welcome to contribute too, if you feel like implementing any feature or you end up changing it anyway.
